# 自动求导/Autograd

In [4]:
import torch

## Autograd

计算梯度依赖于 grad_fn，它是一个属性，指向创建 Tensor 的 Function（除非用户创建的 Tensor，即这个 Tensor 的 grad_fn 是 None ）。

In [6]:
_x = torch.randn((3, 3), requires_grad=True)
print(_x)
print(_x.grad_fn)

tensor([[-0.6456, -0.3130,  0.2084],
        [-1.2264,  0.5803,  0.8045],
        [-0.8767, -0.0387,  0.2136]], requires_grad=True)
None


In [37]:
_x = torch.ones((2, 2), requires_grad=True)
print(_x)
_y = _x**2
print(_y)
print(_y.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)


In [38]:
_z = _y * _y * 3
print(_z)
_mean = _z.mean()
print(_mean)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<MulBackward0>)
tensor(3., grad_fn=<MeanBackward0>)


## Gradiant

> TODO: 资料损坏，等待使用

In [39]:
out = _mean.clone()
print(out.backward())
#print(_mean.grad.data)

None
