# Tensor

## Constructor

In [2]:
import torch

# Zero Matrix
x = torch.zeros((4, 3), dtype=torch.float) # 4x3
print("zeros =", x)

# One Matrix
o = torch.ones((7, 1), dtype=torch.float32) # Consider  7, 1 -> 7 items, each item 1 1 ite 
print("ones =", o)

# Rand Matrix
r = torch.rand((2, 3, 4), dtype=torch.float16)
print("rands =", r)

zeros = tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
ones = tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])
rands = tensor([[[0.7983, 0.3442, 0.9375, 0.9814],
         [0.0347, 0.3188, 0.3247, 0.1338],
         [0.8950, 0.6060, 0.7700, 0.2349]],

        [[0.6265, 0.0537, 0.7871, 0.7285],
         [0.9937, 0.7114, 0.1416, 0.4878],
         [0.1362, 0.9683, 0.6353, 0.9102]]], dtype=torch.float16)


In [47]:
x = torch.randn_like(x) # make x randomise
print(x)

tensor([[ 6.2142e-01,  3.9220e-01,  1.0477e+00],
        [-1.0433e+00, -1.5716e+00, -9.9595e-01],
        [ 5.3391e-01, -7.4543e-04, -1.5879e+00],
        [ 1.0445e+00, -9.9226e-01, -1.0165e+00]])


In [48]:
# Size
def _foo_size(m: torch.tensor):
    print("Tensor =", m, "\nSize =", m.size())

_foo_size(x) # 4 x 3
_foo_size(o) # 7 x 1
_foo_size(r) # 2 x 3 x 4

Tensor = tensor([[ 6.2142e-01,  3.9220e-01,  1.0477e+00],
        [-1.0433e+00, -1.5716e+00, -9.9595e-01],
        [ 5.3391e-01, -7.4543e-04, -1.5879e+00],
        [ 1.0445e+00, -9.9226e-01, -1.0165e+00]]) 
Size = torch.Size([4, 3])
Tensor = tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]) 
Size = torch.Size([7, 1])
Tensor = tensor([[[0.5835, 0.4961, 0.1367, 0.8608],
         [0.2852, 0.2070, 0.0776, 0.6562],
         [0.6187, 0.4692, 0.2090, 0.1987]],

        [[0.2202, 0.1401, 0.8916, 0.1113],
         [0.8823, 0.6904, 0.8438, 0.5273],
         [0.1401, 0.2495, 0.4194, 0.7349]]], dtype=torch.float16) 
Size = torch.Size([2, 3, 4])


### Some functions

| 函数 | 备注 |
| --- | --- |
| `Tensor(sizes)` | 基础构造函数 |
| `tensor(data)` | 类似于np.array |
| `ones(sizes)` | 全1 |
| `zeros(sizes)` | 全0 |
| `eye(sizes)` | 对角为1，其余为0 |
| `arange(s,e,step)` | 从s到e，步长为step |
| `linspace(s,e,steps)` | 从s到e，均匀分成step份 |
| `rand/randn(sizes)` | rand是 \[0,1\) 均匀分布；randn是服从N(0，1)的正态分布 |
| `normal(mean,std)` | 正态分布(均值为mean，标准差是std) |
| `randperm(m)` | 随机排列 |

## Operation

In [49]:
import torch

_o1 = torch.rand((4, 3), dtype=torch.float64)
_o2 = torch.ones((4, 3), dtype=torch.float32)
print("Oper1 =", _o1)
print("Oper2 =", _o2)
_r1 = _o1 + _o2
print("O1 + O2 =", _r1)
_r2 = _o2 + _o1
print("O2 + O1 =", _r2)

_o1.add(_o2)
print("add(self) =", _o1)
_o1.add_(_o2)
print("add_(self) =", _o1)

Oper1 = tensor([[0.4606, 0.3432, 0.4596],
        [0.4213, 0.0074, 0.5885],
        [0.8503, 0.1651, 0.0275],
        [0.2428, 0.6862, 0.8944]], dtype=torch.float64)
Oper2 = tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
O1 + O2 = tensor([[1.4606, 1.3432, 1.4596],
        [1.4213, 1.0074, 1.5885],
        [1.8503, 1.1651, 1.0275],
        [1.2428, 1.6862, 1.8944]], dtype=torch.float64)
O2 + O1 = tensor([[1.4606, 1.3432, 1.4596],
        [1.4213, 1.0074, 1.5885],
        [1.8503, 1.1651, 1.0275],
        [1.2428, 1.6862, 1.8944]], dtype=torch.float64)
add(self) = tensor([[0.4606, 0.3432, 0.4596],
        [0.4213, 0.0074, 0.5885],
        [0.8503, 0.1651, 0.0275],
        [0.2428, 0.6862, 0.8944]], dtype=torch.float64)
add_(self) = tensor([[1.4606, 1.3432, 1.4596],
        [1.4213, 1.0074, 1.5885],
        [1.8503, 1.1651, 1.0275],
        [1.2428, 1.6862, 1.8944]], dtype=torch.float64)


In [50]:
_idx = torch.randn(4, 3, 2)
print(_idx)
print(_idx[:, 2])
print(_idx[1])
print(_idx[1, :])
print(_idx[1, :, 0])

tensor([[[-0.8907,  0.4556],
         [-0.3702, -0.8383],
         [ 0.5508, -0.2645]],

        [[ 2.1586, -1.4386],
         [ 0.2899, -0.1456],
         [ 0.7341,  0.8412]],

        [[ 0.3454, -0.6233],
         [-1.6413, -0.5500],
         [ 0.1116,  1.7938]],

        [[-0.4579,  1.6365],
         [-1.2949, -0.7643],
         [-0.0401, -0.5374]]])
tensor([[ 0.5508, -0.2645],
        [ 0.7341,  0.8412],
        [ 0.1116,  1.7938],
        [-0.0401, -0.5374]])
tensor([[ 2.1586, -1.4386],
        [ 0.2899, -0.1456],
        [ 0.7341,  0.8412]])
tensor([[ 2.1586, -1.4386],
        [ 0.2899, -0.1456],
        [ 0.7341,  0.8412]])
tensor([2.1586, 0.2899, 0.7341])


### Reshaping

In [8]:
_view = torch.rand((4, 4))
print(_view)

print(_view.view(16))
print(_view.view(2, -1))
print(_view.view(-1, 17)) # invalid

tensor([[0.7361, 0.4630, 0.7515, 0.9819],
        [0.2536, 0.0166, 0.5600, 0.8375],
        [0.9675, 0.3923, 0.3063, 0.5710],
        [0.4708, 0.1323, 0.2812, 0.0552]])
tensor([0.7361, 0.4630, 0.7515, 0.9819, 0.2536, 0.0166, 0.5600, 0.8375, 0.9675,
        0.3923, 0.3063, 0.5710, 0.4708, 0.1323, 0.2812, 0.0552])
tensor([[0.7361, 0.4630, 0.7515, 0.9819, 0.2536, 0.0166, 0.5600, 0.8375],
        [0.9675, 0.3923, 0.3063, 0.5710, 0.4708, 0.1323, 0.2812, 0.0552]])


RuntimeError: shape '[-1, 17]' is invalid for input of size 16

In [16]:
_arrange = torch.arange(0, 3, 1).view(3, 1)
print(_arrange)
_addOn = torch.tensor([0, 1])
print(_addOn)
_out = _arrange + _addOn
print(_out)

tensor([[0],
        [1],
        [2]])
tensor([0, 1])
tensor([[0, 1],
        [1, 2],
        [2, 3]])
