# 损失函数

In [1]:
import torch
from torch import nn

## BCELoss (Binary Cross Entropy Loss)

$$
L=\frac{1}{N}\sum_{i=1}^N -[y_i\log(p_i)+(1-y_i)\log(1-p_i)]
$$

- $y_i$: 样本i的真实标签（0或者1）
- $p_i$: 样本i预测为正样本的概率

SUM 模式


$$
l(X, Y) = \begin{cases}
    \text{mean}(L)         & \text{if reduction = 'mean'} \\
    \text{sum }(L)         & \text{if reduction = 'sum' }
\end{cases}
$$

In [11]:
active = nn.Sigmoid()
loss = nn.BCELoss()

input = torch.randn(3, requires_grad=True)
print('input =\n', input)

target = torch.empty(3).random_(2) # random_(N) 是表示从 [0, N) 进行随机
print('target =\n', target)

output = loss(active(input), target)
output.backward()

print('BCELoss() =\n', output)

input =
 tensor([ 0.1679, -0.0870, -0.7915], requires_grad=True)
target =
 tensor([1., 0., 0.])
BCELoss() =
 tensor(0.5457, grad_fn=<BinaryCrossEntropyBackward0>)


## CrossEntropyLoss

$$
\begin{aligned}
L &= \frac{1}{N}\sum_i^N L_i \\
  &= \frac{1}{N}\sum_{c=1}^C [y_{ic} \log(p_{ic})]
\end{aligned}
$$

- C: 类别数
- $y_{ic}$: bool, 如果样本 i 真实类别为 c，则为 1，否则为 0
- $p_{ic}$: 样本 i 预测为类别 c 的概率

In [15]:
loss = nn.CrossEntropyLoss()

input = torch.randn(3, 5, requires_grad=True)
print('input =\n', input)

target = torch.empty(3, dtype=torch.long).random_(5)
print('target =\n', target)

output = loss(input, target)
output.backward()
print('CELoss() =\n', output)

input =
 tensor([[ 0.2775, -1.1323,  0.7124, -2.1484,  0.4200],
        [-1.7906, -0.6312, -0.2453,  0.6484, -1.0162],
        [-0.7919, -0.1500,  0.6598, -1.1956, -0.8249]], requires_grad=True)
target =
 tensor([1, 4, 2])
CELoss() =
 tensor(1.9556, grad_fn=<NllLossBackward0>)


## L1 Loss

$$
L=\mid \hat{y}-y \mid
$$

In [16]:
loss = nn.L1Loss()

input = torch.randn(3, 5, requires_grad=True)
print('input =\n', input)

target = torch.randn(3, 5)
print('target =\n', target)

output = loss(input, target)
output.backward()
print('L1() =\n', output)

input =
 tensor([[-1.7635,  0.1556, -0.6223, -0.7268, -1.2946],
        [-1.7378,  0.1661, -1.0814, -1.1439,  0.5920],
        [ 0.1332, -1.1221,  0.3395, -0.3578, -0.0967]], requires_grad=True)
target =
 tensor([[ 1.8535, -1.1770, -0.1588, -1.2424,  0.9354],
        [-0.0087, -1.8183,  2.1992, -0.3471, -0.7438],
        [-0.1790, -0.8815, -0.2270, -0.3427, -0.4090]])
L1() =
 tensor(1.2488, grad_fn=<MeanBackward0>)


## MSE/L2 Loss

$$
L = (\hat{y}-y)^2
$$

In [17]:
loss = nn.MSELoss()

input = torch.randn(3, 5, requires_grad=True)
print('input =\n', input)

target = torch.randn(3, 5)
print('target =\n', target)

output = loss(input, target)
output.backward()
print('L1() =\n', output)

input =
 tensor([[-0.5070,  0.4369, -0.1781,  0.0681, -0.4557],
        [-1.2526,  0.3511, -0.5278, -0.0536,  1.5063],
        [-0.5172,  0.6655, -0.0341,  0.3643,  0.5832]], requires_grad=True)
target =
 tensor([[ 1.0522,  2.3562,  0.0837,  2.3595,  0.2934],
        [ 0.2369, -2.0097, -1.2394, -0.2212,  0.4254],
        [ 1.8768,  0.0744, -1.2391, -0.0936, -1.4914]])
L1() =
 tensor(2.2358, grad_fn=<MseLossBackward0>)
