# Module

In [2]:
import torch
from torch import nn

In [9]:
class MLP(nn.Module):
    def __init__(self, **kwargs):
        super(MLP, self).__init__(**kwargs)
        self.hidden = nn.Linear(784, 256)
        self.act = nn.ReLU()
        self.output = nn.Linear(256, 10)
        
    def forward(self, x):
        o = self.act(self.hidden(x))
        return self.output(o)

In [14]:
net = MLP()
X = torch.randn((2, 784))
print(net)
print(net(X)) # Forward

MLP(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (act): ReLU()
  (output): Linear(in_features=256, out_features=10, bias=True)
)
tensor([[-0.1892, -0.2588, -0.0780, -0.1015, -0.2894, -0.2577, -0.2746, -0.4146,
         -0.1739, -0.0106],
        [-0.0869, -0.2304,  0.2543, -0.1979, -0.1368, -0.3127, -0.2208, -0.2112,
         -0.3587,  0.4316]], grad_fn=<AddmmBackward0>)


In [19]:
class MinusMean(nn.Module):
    def __init__(self, **kargs):
        super(MinusMean, self).__init__(**kargs)
    
    def forward(self, x):
        mean = x.mean()
        return x - mean

net = MinusMean()
X = torch.arange(0, 6, 2, dtype=torch.float32)
print(X)
print(net(X))

tensor([0., 2., 4.])
tensor([-2.,  0.,  2.])
